metrics: true
ownerProtection: true
maxPlayerChest: 3
Gui:
  title: "&7&lHopeChest &0Assignment"
  MobHead:
    name: "{mob}"
    lore:
      - "&7Right Click: &fGet the token item in your inventory"
  Crop:
    cactus:
      id: cactus
    sugar_cane:
      id: sugar_cane
    melon:
      id: melon
    pumpkin:
      id: pumpkin
    crops:
      id: wheat
    cocoa:
      id: ink_sack
      data: 3
    potato:
      id: potato_item
    carrot:
      id: carrot_item
    nether_warts:
      id: nether_stalk
    beetroot_block:
      id: beetroot
      
TokenItem:
  id: paper
  name: "{chest} &7Token"
  lore:
    - "&7Shift + Right Click &fon a {chest}"
    - "&7To add {type} &7to it!"

AutoSell:
  sellDelay: 30 #Chests sell delay in seconds.
  Gui:
    title: "AutoSell Gui: {sell_time}"
    onItem:
      id: wool
      data: 13
      name: "&7AutoSell Mode: &2ON"
    offItem:
      id: wool
      data: 7
      name: "&7AutoSell Mode: &cOFF"
      
HeadHunting:
  enabled: true
  alwaysDrop: true #This will enable heads to be dropped also when a mob is normally killed.
  MobHead:
    name: "{mob}&7's Head"
    lore:
      - "&fRight click to sell"
      - "&7Sell for: {cost}" 
  HeadValues:
    bat: 1.0
    blaze: 16.0
    spider: 4.0
    cave_spider: 4.5
    chicken: 2.0
    cow: 2.25
    mushroom_cow: 2.5
    creeper: 5.0
    enderman: 7.0
    endermite: 3.5
    ghast: 8.0
    guardian: 10.0
    elder_guardian: 14.0
    horse: 3.0
    skeleton_horse: 3.25
    zombie_horse: 3.5
    mule: 3.0
    donkey: 3.0
    llama: 3.0
    iron_golem: 16.0
    snowman: 5.0
    ocelot: 3.0
    parrot: 1.5
    pig: 2.0
    polar_bear: 9.0
    rabbit: 1.5
    sheep: 2.0
    shulker: 9.5
    silverfish: 6.0
    skeleton: 4.5
    wither_skeleton: 6.0
    stray: 6.0
    slime: 0.75
    magma_cube: 1.15
    squid: 2.0
    villager: 1.0
    vindicator: 24.0
    evoker: 24.0
    illusioner: 24.0
    vex: 5.0
    witch: 8.0
    wolf: 2.75
    zombie: 4.0
    zombie_villager: 4.5
    pig_zombie: 7.0
    giant: 50.0
    husk: 6.0
    wither: 300.0
    ender_dragon: 2500.0
    
Mob:
  ChestItem:
    id: chest #This must be a valid container. If is not, the plugin won't start.
    name: "&bMob&fChest"
    lore:
      - "&fA special chest that contains some teleport powers,"
      - "&fwill gather all drops from nearby &bmobs&f."
      - ""
      - "&7Shift + Right &fClick to configure."
  itemBlacklist:
      - red_rose
      
  MobNames:
    bat: "&fBat"
    blaze: "&dBlaze"
    spider: "&aSpider"
    cave_spider: "&aCave Spider"
    chicken: "&fChicken"
    cow: "&fCow"
    mushroom_cow: "&dMushroom &fCow"
    creeper: "&2Creeper"
    enderman: "&5Enderman"
    endermite: "&5Endermite"
    ghast: "&fGhast"
    guardian: "&3Guardian"
    elder_guardian: "&3Elder Guardian"
    horse: "&7Horse"
    skeleton_horse: "&7Skeleton Horse"
    zombie_horse: "&7Zombie Horse"
    mule: "&7Mule"
    donkey: "&7Donkey"
    llama: "&7Llama"
    iron_golem: "&8Iron Golem"
    snowman: "&7SnowMan"
    ocelot: "&7Ozelot"
    parrot: "&7Parrot"
    pig: "&5Pig"
    polar_bear: "&fPolar Bear"
    rabbit: "&fRabbit"
    sheep: "&fSheep"
    shulker: "&dShulker"
    silverfish: "&7Silverfish"
    skeleton: "&7Skeleton"
    wither_skeleton: "&0Wither Skeleton"
    stray: "&7Stray"
    slime: "&aSlime"
    magma_cube: "&4Magma Cube"
    squid: "&1Squid"
    villager: "&fVillager"
    vindicator: "&eVindicator"
    evoker: "&eEvoker"
    illusioner: "&eIllusioner"
    vex: "&eVex"
    witch: "&dWitch"
    wolf: "&7Wolf"
    zombie: "&aZombie"
    zombie_villager: "&aZombie Villager"
    pig_zombie: "&5Pig Zombie"
    giant: "&2Giant"
    husk: "&2Husk"
    wither: "&0Wither"
    ender_dragon: "&dEnder Dragon"
  
Crop:
  ChestItem:
    id: chest #This must be a valid container. If is not, the plugin won't start.
    name: "&bCrop&fChest"
    lore:
      - "&fA special chest that contains some teleport powers,"
      - "&fwill gather all drops from &2growing crops&f."
      - ""
      - "&7Shift + Right &fClick to configure."
  CropNames:
    cactus: "&2Cactus"
    sugar_cane: "&2SugarCane"
    melon: "&2Melons"
    pumpkin: "&ePumpkins"
    crops: "&eWheat"
    cocoa: "&7Cocoa Beans"
    potato: "&2Potato"
    carrot: "&2Carrot"
    nether_warts: "&4Nether &cWarts"
    beetroot_block: "&cBeetroot"
      
Language: #Leave the message empty (Set it "") or remove it for not have the message to be sent.
  command_getchest: "&7/hchest getchest <type> <subType1> <subType2> ... &2- Get an empty &7&lHopeChest&f."
  command_givechest: "&7/hchest givechest <player> <type> <subType1> <subType2> ... &2- Give an empty &7&lHopeChest &2to a player."
  command_gettoken: "&7/hchest gettoken <type> <subType> &2- Get a chest token."
  command_givetoken: "&7/hchest givetoken <player> <type> <subType> &2- Give a chest token to a player."
  command_playerchest: "&7/hchest playerchest <player> &2- Get all placed chest of a player (Clickable messages)"
  command_reload: "&7/hchest reload &2- Reload the configuration."
  command_wrong: "&7There is not such command as {command}. Use &f/hchest help &7for info."
  command_error: "&4Something went wrong while executing the command."
  configuration_reloaded: "&2You have succesfully reloaded the configuration."
  configuration_reload_error: "&cSomething went wrong while reloading the configuration."
  wrong_subtype: "&cThe subType {type} is wrong."
  wrong_token_type: "&cThis token is of wrong type. It is assigned to {chest}&c."
  no_playerchest_found: "&2{player} &fhas not placed HopeChest."
  clickable_playerchest_message: "&fX:&l{x} &fY:&l{y} &fZ:&l{z} &fWorld:&l{world} &0(&7ClickMe!&0)"
  token_subtype_already_exist: "&cThat chest already have the subType of this token."
  max_chest_exceeded: "&cYou have reached the limit of 4 &7HopeChest &cplaced."
  player_not_owner: "&cYou are not the owner of this {chest}&c."
  player_offline: "&2{player} &cis offline."
  no_permission: "&cYou don't have the permission to do that."
  no_such_chesttype: "&cA chest type named &4&l{name} &cdoes not exists."
  heads_sold: "&fYou have sold x&l{amount}&f heads for &2&l{money}&f."
  item_sent: "&fYou sent {item} &fto &2{player}&f."
  item_received: "&fYou received {item}&f."
  inventory_full: "&fYour inventory was full. The received item is being dropped on the ground."
  chest_placed: "&fYou have placed a {chest}&f."
  chest_destroyed: "&cYou have destroyed a {chest}&f"
  cropchest: "&2Crop&7Chest"
  mobchest: "&bMob&7Chest"
  generic_error: "&4Something went wrong. Contact an admin."