name: HopeChest
version: 4.0
main: me.parozzz.hopechest.HopeChest
commands:
  chest:
    aliases: [hpc,ch,assignchest]
    usage: /chest help
    description: Main command
depend: [ReflexAPI]
softdepend: [Vault, Multiverse-Core]
