name: HopeChest
version: 4.0
description: Create chest that gather stuff!
author: Parozzz
website: https://github.com/Parozzz/HopeItems

load: STARTUP
main: me.parozzz.hopechest.HopeChest

depend: [ReflexAPI]
softdepend: [StackMob, Multiverse-Core]
